package com.tonaco.tns;
public enum TokenType {
    PRINT, LET, IF, ELSE, WHILE, FOR, FUNCTION, RETURN,
    TRUE, FALSE, NULL,
    SCAN, DEEPSCAN, DOWNLOAD, ANALYZE, GITHUB, REPORT, SYNC, SHARE,
    IDENTIFIER, STRING, NUMBER,
    PLUS, MINUS, MULTIPLY, DIVIDE, MODULO,
    ASSIGN, EQUALS, NOT_EQUALS,
    LESS, GREATER, LESS_EQUAL, GREATER_EQUAL,
    AND, OR, NOT,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    COMMA, SEMICOLON, COLON, DOT,
    EOF, ERROR
}
